name: Deploy Website to cPanel via FTP

on:
  push:
    branches:
      - main  # Robot akan berjalan setiap kali ada perubahan di branch 'main'

jobs:
  web-deploy:
    name: 🚀 Deploying latest code
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Jika Anda ingin menghapus file di hosting yang sudah tidak ada di GitHub, ubah false jadi true
        delete-removed: false
